apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mgaz46o32-python 
  janus-idp.io/tekton: mgaz46o32-python
  backstage.io/kubernetes-id: mgaz46o32-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mgaz46o32-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml