apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mgaz46o32-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mgaz46o32-python 
  name: mgaz46o32-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mgaz46o32-python 
